on:
  workflow_dispatch:
    inputs:
      gutenbergMobileSha:
        description: "The SHA for the Mobile Gutenberg commit to build."
        required: true
      prTitle:
        description: "The title of the pull request."
        required: true
        default: "test"
      prBody:
        description: "The body of the pull request."
        required: true
        default: "test"
      headBranch:
        description: "The branch to commit build changes."
        required: true
        default: "test"
      baseBranch:
        description: "The branch into which the build will be merged."
        required: false
        default: "develop"

jobs:
  update_gutenberg:
    runs-on: macos-11
    name: Update Gutenberg
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEAD: ${{ github.event.inputs.headBranch }}
      GBM_SHA: ${{ github.event.inputs.gutenbergMobileSha }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Branch
        run: |
          git pull origin $HEAD && git switch $HEAD || git switch -c $HEAD

      - name: Update Podfile
        id: podfile
        run: |
          sed -i '' -E "s/gutenberg :(commit|tag) => '(.*)'/gutenberg :commit => '$GBM_SHA'/" Podfile
          # Exit if there are no changes
          did_change=$(git diff --exit-code && echo "false" || echo "true")
          if [ "$did_change" == "false" ]; then
            echo "No changes to commit."
          fi
          echo ::set-output name=didChange::$did_change

      # - name: Install Gems and Pods
      #  run: bundle install && bundle exec pod install

      - name: Push Changes and Create Pull Request
        if: ${{ steps.podfile.outputs.didChange == 'true' }}
        run: |
          git commit -am "Update Gutenberg to $GBM_SHA" && git push origin $HEAD
          gh pr create \
          --title "${{ github.event.inputs.prTitle }}" \
          --body "${{ github.event.inputs.prBody }}" \
          --base "${{ github.event.inputs.baseBranch }}" || true
