on:
  workflow_dispatch:
    inputs:
      gutenbergMobileShaOrPrUrl:
        description: "The SHA or PR Url for the Mobile Gutenberg commit to build."
        required: true
      prTitle:
        description: "The title of the pull request."
        required: true
        default: "test"
      prBody:
        description: "The body of the pull request."
        required: true
        default: "test"
      headBranch:
        description: "The branch to commit build changes."
        required: true
        default: "test"
      baseBranch:
        description: "The branch into which the build will be merged."
        required: false
        default: "develop"

jobs:
  update_gutenberg:
    runs-on: macos-11
    name: Update Gutenberg
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEAD: ${{ github.event.inputs.headBranch }}
    steps:
      - uses: actions/checkout@v2

      - name: Find Gutenberg Mobile commit
        id: gbm_pr
        run: |
          sha_or_url=${{ github.event.inputs.gutenbergMobileShaOrPrUrl}}
          if [[ $sha_or_url =~ '^https://github.com' ]] ;then
            gbm_sha=$(gh api repos/${sha_or_url#https://github.com/} --jq '.head.sha')
          else
            gbm_sha=$(echo $sha_or_url | xargs)
          fi
          echo ::set-output name=gbm_sha::$gbm_sha
        env:
          GITHUB_TOKEN: ${{ secrets.WORDPRESS_MOBILE_GITHUB_TOKEN }}

      - name: Checkout Branch
        run: |
          git pull origin $HEAD && git switch $HEAD || git switch -c $HEAD

      - name: Update Podfile
        run: |
          gbm_sha=${{ steps.gbm_pr.outputs.gbm_sha }}
          sed -i '' -E "s/gutenberg :(commit|tag) => '(.*)'/gutenberg :commit => '$gbm_sha'/" Podfile

      - name: Install Gems and Pods
        id: bundle
        run: |
          bundle install && bundle exec pod install
          echo ::set-output name=didChange::$(git diff --exit-code && echo "false" || echo "true")

      - name: Push Changes and Create Pull Request
        if: ${{ steps.bundle.outputs.didChange == 'true' }}
        run: |
          git commit -am "Update Gutenberg to $GBM_SHA" && git push origin $HEAD
          gh pr create \
          --title "${{ github.event.inputs.prTitle }}" \
          --body "${{ github.event.inputs.prBody }}" \
          --base "${{ github.event.inputs.baseBranch }}" || true

      - name: Update Mobile Gutenberg PR
        if: ${{ github.event.inputs.gutenbergMobilePR }}
        run: |

        env:
          GITHUB_TOKEN: ${{ secrets.WORDPRESS_MOBILE_GITHUB_TOKEN }}
